# nixpacks.toml (Versão Corrigida e Simplificada)

[processes]
# Diz ao processo 'web' (que o Nixpacks detecta automaticamente para o Laravel)
# para usar a pasta /app/public como sua raiz.
web.rootDir = "/app/public"